In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.float_forma', '{:.2}'.format)

In [2]:
df_raw = pd.read_csv(r"A:\IBM HR Analytics\Dataset\HR-Employee-Attrition.csv")

In [3]:
print(f'shape: {df_raw.shape}')
print(f'rows: {len(df_raw)}')
print(f'columns: {df_raw.shape[1]}')

shape: (1470, 35)
rows: 1470
columns: 35

## First Inspection

In [4]:
df_raw.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

In [5]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [6]:
df_raw.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [7]:
print(df_raw.columns.tolist())

['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department', 'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

### Problem 1

In [8]:
print(df_raw['Over18'].value_counts())
print(df_raw['EmployeeCount'].value_counts())
print(df_raw['StandardHours'].value_counts())

Over18
Y    1470
Name: count, dtype: int64
EmployeeCount
1    1470
Name: count, dtype: int64
StandardHours
80    1470
Name: count, dtype: int64

All three columns have 1 value and are not useful for our analysis  so we will drop these 3 columns

### Problem 2

In [9]:
df_raw['Attrition'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1470 entries, 0 to 1469
Series name: Attrition
Non-Null Count  Dtype
--------------  -----
1470 non-null   object
dtypes: object(1)
memory usage: 11.6+ KB

Attrition column is object type we need to convert it to numeric to build models.

### Problem 3

Column names are in CamelCase, we need to convert these name to snake_case for SQL queries.

### Droping useless columns

In [10]:
df = df_raw.copy()
col_to_drop = ['Over18', 'EmployeeCount', 'StandardHours']
df.drop(columns=col_to_drop, inplace= True)

print(f'shape after drop: {df.shape}')
print(f'Dropped Coumns: {col_to_drop}')

shape after drop: (1470, 32)
Dropped Coumns: ['Over18', 'EmployeeCount', 'StandardHours']

### Converting Attrition column to Binary

In [11]:
df['Attrition'] = df['Attrition'].map({'Yes':1, 'No': 0})

print(df['Attrition'].value_counts())
print(f'Attrition Rate: {df['Attrition'].mean()*100:.1f}%')

Attrition
0    1233
1     237
Name: count, dtype: int64
Attrition Rate: 16.1%

### Changing Column Names to snake_case

In [12]:
df.rename(columns={
    'Age'                      : 'age',
    'Attrition'                : 'attrition',
    'BusinessTravel'           : 'business_travel',
    'DailyRate'                : 'daily_rate',
    'Department'               : 'department',
    'DistanceFromHome'         : 'distance_from_home',
    'Education'                : 'education',
    'EducationField'           : 'education_field',
    'EmployeeNumber'           : 'employee_id',
    'EnvironmentSatisfaction'  : 'environment_satisfaction',
    'Gender'                   : 'gender',
    'HourlyRate'               : 'hourly_rate',
    'JobInvolvement'           : 'job_involvement',
    'JobLevel'                 : 'job_level',
    'JobRole'                  : 'job_role',
    'JobSatisfaction'          : 'job_satisfaction',
    'MaritalStatus'            : 'marital_status',
    'MonthlyIncome'            : 'monthly_income',
    'MonthlyRate'              : 'monthly_rate',
    'NumCompaniesWorked'       : 'num_companies_worked',
    'OverTime'                 : 'overtime',
    'PercentSalaryHike'        : 'percent_salary_hike',
    'PerformanceRating'        : 'performance_rating',
    'RelationshipSatisfaction' : 'relationship_satisfaction',
    'StockOptionLevel'         : 'stock_option_level',
    'TotalWorkingYears'        : 'total_working_years',
    'TrainingTimesLastYear'    : 'training_times_last_year',
    'WorkLifeBalance'          : 'work_life_balance',
    'YearsAtCompany'           : 'years_at_company',
    'YearsInCurrentRole'       : 'years_in_current_role',
    'YearsSinceLastPromotion'  : 'years_since_last_promotion',
    'YearsWithCurrManager'     : 'years_with_curr_manager',}, inplace=True)

print(df.columns.tolist())
print(f'Shape still: {df.shape}')

['age', 'attrition', 'business_travel', 'daily_rate', 'department', 'distance_from_home', 'education', 'education_field', 'employee_id', 'environment_satisfaction', 'gender', 'hourly_rate', 'job_involvement', 'job_level', 'job_role', 'job_satisfaction', 'marital_status', 'monthly_income', 'monthly_rate', 'num_companies_worked', 'overtime', 'percent_salary_hike', 'performance_rating', 'relationship_satisfaction', 'stock_option_level', 'total_working_years', 'training_times_last_year', 'work_life_balance', 'years_at_company', 'years_in_current_role', 'years_since_last_promotion', 'years_with_curr_manager']
Shape still: (1470, 32)

## Inspecting Categorical Columns

In [13]:
categorical_cols = df.select_dtypes(include='object').columns.tolist()
for col in categorical_cols:
    print(f'\n{col}:')
    print(df[col].value_counts())

business_travel:
business_travel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

department:
department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

education_field:
education_field
Life Sciences       606
Medical             464
Marketing           159
Technical Degree    132
Other                82
Human Resources      27
Name: count, dtype: int64

gender:
gender
Male      882
Female    588
Name: count, dtype: int64

job_role:
job_role
Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: count, dtype: int64

marital_status:
marital_status
Married     673
Single      470
Divorced    327
Name: count, dtype: int64

overtime:
overtime
No     1054
Yes     416
Name: count, dtype: int64

There are no inconsistencies in categorical columns.

### Checking numerical ranges for anamolies

In [14]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,1.5e+03,3.7e+01,9.1,1.8e+01,3e+01,3.6e+01,4.3e+01,6e+01
attrition,1.5e+03,0.16,0.37,0.0,0.0,0.0,0.0,1.0
daily_rate,1.5e+03,8e+02,4e+02,1e+02,4.6e+02,8e+02,1.2e+03,1.5e+03
distance_from_home,1.5e+03,9.2,8.1,1.0,2.0,7.0,1.4e+01,2.9e+01
education,1.5e+03,2.9,1.0,1.0,2.0,3.0,4.0,5.0
employee_id,1.5e+03,1e+03,6e+02,1.0,4.9e+02,1e+03,1.6e+03,2.1e+03
environment_satisfaction,1.5e+03,2.7,1.1,1.0,2.0,3.0,4.0,4.0
hourly_rate,1.5e+03,6.6e+01,2e+01,3e+01,4.8e+01,6.6e+01,8.4e+01,1e+02
job_involvement,1.5e+03,2.7,0.71,1.0,2.0,3.0,3.0,4.0
job_level,1.5e+03,2.1,1.1,1.0,1.0,2.0,3.0,5.0
job_satisfaction,1.5e+03,2.7,1.1,1.0,2.0,3.0,4.0,4.0
monthly_income,1.5e+03,6.5e+03,4.7e+03,1e+03,2.9e+03,4.9e+03,8.4e+03,2e+04
monthly_rate,1.5e+03,1.4e+04,7.1e+03,2.1e+03,8e+03,1.4e+04,2e+04,2.7e+04
num_companies_worked,1.5e+03,2.7,2.5,0.0,1.0,2.0,4.0,9.0
percent_salary_hike,1.5e+03,1.5e+01,3.7,1.1e+01,1.2e+01,1.4e+01,1.8e+01,2.5e+01
performance_rating,1.5e+03,3.2,0.36,3.0,3.0,3.0,3.0,4.0
relationship_satisfaction,1.5e+03,2.7,1.1,1.0,2.0,3.0,4.0,4.0
stock_option_level,1.5e+03,0.79,0.85,0.0,0.0,1.0,1.0,3.0
total_working_years,1.5e+03,1.1e+01,7.8,0.0,6.0,1e+01,1.5e+01,4e+01
training_times_last_year,1.5e+03,2.8,1.3,0.0,2.0,3.0,3.0,6.0
work_life_balance,1.5e+03,2.8,0.71,1.0,2.0,3.0,3.0,4.0
years_at_company,1.5e+03,7.0,6.1,0.0,3.0,5.0,9.0,4e+01
years_in_current_role,1.5e+03,4.2,3.6,0.0,2.0,3.0,7.0,1.8e+01
years_since_last_promotion,1.5e+03,2.2,3.2,0.0,0.0,1.0,3.0,1.5e+01
years_with_curr_manager,1.5e+03,4.1,3.6,0.0,2.0,3.0,7.0,1.7e+01

In [15]:
print('Education (1-5):', df['education'].unique())
print('Job Level (1-5):', df['job_level'].unique())
print('Job Satisfaction (1-4):', df['job_satisfaction'].unique())
print('Performance Rating:', df['performance_rating'].unique())
print('Stock Option Level:', df['stock_option_level'].unique())
print('Work Life Balance (1-4):', df['work_life_balance'].unique())

Education (1-5): [2 1 4 3 5]
Job Level (1-5): [2 1 3 4 5]
Job Satisfaction (1-4): [4 2 3 1]
Performance Rating: [3 4]
Stock Option Level: [0 1 3 2]
Work Life Balance (1-4): [1 3 2 4]

### Creating Department lookup table

In [16]:
departments = df[['department']].drop_duplicates().reset_index(drop=True)
departments.insert(0,'department_id',range(1,len(departments)+1))

print(departments)

   department_id              department
0              1                   Sales
1              2  Research & Development
2              3         Human Resources

### Adding department_id to main dataframe

In [17]:
dept_map = departments.set_index('department')['department_id'].to_dict()
df['department_id'] = df['department'].map(dept_map)

In [18]:
print(df[['department', 'department_id']].drop_duplicates())
print(f'Any nulls in department_id: {df["department_id"].isnull().sum()}')

                department  department_id
0                    Sales              1
1   Research & Development              2
79         Human Resources              3
Any nulls in department_id: 0

## Creating 4 DataFrames for SQL

### Table 1 - Employees

In [19]:
employees = df[[
    'employee_id',
    'age',
    'gender',
    'marital_status',
    'education',
    'education_field',
    'distance_from_home',
    'num_companies_worked',
    'total_working_years',
    'department_id',
    'attrition'
]].copy()

print(f'employees: {employees.shape}')
print(employees.head(3))

employees: (1470, 11)
   employee_id  age  gender marital_status  education education_field  \
0            1   41  Female         Single          2   Life Sciences
1            2   49    Male        Married          1   Life Sciences
2            4   37    Male         Single          2           Other

   distance_from_home  num_companies_worked  total_working_years  \
0                   1                     8                    8
1                   8                     1                   10
2                   2                     6                    7

   department_id  attrition
0              1          1
1              2          0
2              2          1

### Table 2 - Job_details

In [20]:
job_details = df[[
    'employee_id',
    'job_role',
    'job_level',
    'business_travel',
    'overtime',
    'monthly_income',
    'hourly_rate',
    'daily_rate',
    'monthly_rate',
    'percent_salary_hike',
    'stock_option_level',
    'training_times_last_year',
    'years_at_company',
    'years_in_current_role',
    'years_since_last_promotion',
    'years_with_curr_manager'
]].copy()

print(f'job_details: {job_details.shape}')
print(job_details.head(3))

job_details: (1470, 16)
   employee_id               job_role  job_level    business_travel overtime  \
0            1        Sales Executive          2      Travel_Rarely      Yes
1            2     Research Scientist          2  Travel_Frequently       No
2            4  Laboratory Technician          1      Travel_Rarely      Yes

   monthly_income  hourly_rate  daily_rate  monthly_rate  percent_salary_hike  \
0            5993           94        1102         19479                   11
1            5130           61         279         24907                   23
2            2090           92        1373          2396                   15

   stock_option_level  training_times_last_year  years_at_company  \
0                   0                         0                 6
1                   1                         3                10
2                   0                         3                 0

   years_in_current_role  years_since_last_promotion  years_with_curr_manager
0                      4                           0                        5
1                      7                           1                        7
2                      0                           0                        0

### Table 3 - Satisfaction

In [21]:
satisfaction = df[[
    'employee_id',
    'job_satisfaction',
    'environment_satisfaction',
    'relationship_satisfaction',
    'work_life_balance',
    'job_involvement',
    'performance_rating'
]].copy()

print(f'satisfaction: {satisfaction.shape}')
print(satisfaction.head(3))

satisfaction: (1470, 7)
   employee_id  job_satisfaction  environment_satisfaction  \
0            1                 4                         2
1            2                 2                         3
2            4                 3                         4

   relationship_satisfaction  work_life_balance  job_involvement  \
0                          1                  1                3
1                          4                  3                2
2                          2                  3                2

   performance_rating
0                   3
1                   4
2                   3

### Table 4 - Departments

In [22]:
print(f'departments: {departments.shape}')
print(departments)

departments: (3, 2)
   department_id              department
0              1                   Sales
1              2  Research & Development
2              3         Human Resources

## Final Verification

In [23]:
print('═' * 50)
print('DATAFRAME SUMMARY')
print('═' * 50)

print(f'\nemployees:    {employees.shape[0]:,} rows × {employees.shape[1]} cols')
print(f'job_details:  {job_details.shape[0]:,} rows × {job_details.shape[1]} cols')
print(f'satisfaction: {satisfaction.shape[0]:,} rows × {satisfaction.shape[1]} cols')
print(f'departments:  {departments.shape[0]:,} rows × {departments.shape[1]} cols')

# All employee tables must have same row count
assert len(employees) == len(job_details) == len(satisfaction) == 1470, \
    "Row count mismatch — check your splits"

# No nulls in any primary or foreign key
assert employees['employee_id'].isnull().sum() == 0
assert employees['department_id'].isnull().sum() == 0
assert job_details['employee_id'].isnull().sum() == 0
assert satisfaction['employee_id'].isnull().sum() == 0

# No duplicate employee_ids
assert employees['employee_id'].nunique() == 1470

print('\nAll checks passed. Data is ready for MySQL.')
print(f'\nOverall attrition rate: {employees["attrition"].mean()*100:.1f}%')
print(f'Total attritions: {employees["attrition"].sum()}')
print(f'Total retained: {(employees["attrition"]==0).sum()}')

══════════════════════════════════════════════════
DATAFRAME SUMMARY
══════════════════════════════════════════════════

employees:    1,470 rows × 11 cols
job_details:  1,470 rows × 16 cols
satisfaction: 1,470 rows × 7 cols
departments:  3 rows × 2 cols

All checks passed. Data is ready for MySQL.

Overall attrition rate: 16.1%
Total attritions: 237
Total retained: 1233

Our data is ready for export

In [24]:
employees.to_csv('employees.csv',    index=False)
job_details.to_csv('job_details.csv', index=False)
satisfaction.to_csv('satisfaction.csv', index=False)
departments.to_csv('departments.csv',  index=False)

### Connecting SQL to Python to load data from python to sql

In [ ]:
pip install mysql-connector-python sqlalchemy

In [26]:
from sqlalchemy import create_engine

In [27]:
engine = create_engine('mysql+mysqlconnector://root:Rajat97611@localhost:3306/hr_attrition')

In [28]:
with engine.connect() as conn:
    print("Connection successful")

Connection successful

In [29]:
departments = departments.rename(columns={'department': 'department_name'})
print(departments.columns.tolist())
# Should show: ['department_id', 'department_name']
print(departments)

['department_id', 'department_name']
   department_id         department_name
0              1                   Sales
1              2  Research & Development
2              3         Human Resources

In [ ]:
from sqlalchemy import text

departments.to_sql(
    name='departments',
    con=engine,
    if_exists='append',  
    index=False)

with engine.connect() as conn:
    result = conn.execute(text("SELECT * FROM departments"))
    for row in result:
        print(row)

In [ ]:
employees.to_sql(
    name='employees',
    con=engine,
    if_exists='append',
    index=False
)

with engine.connect() as conn:
    result = conn.execute(text("SELECT COUNT(*) FROM employees"))
    print(f"Employees loaded: {result.fetchone()[0]}")

In [ ]:
job_details.to_sql(
    name='job_details',
    con=engine,
    if_exists='append',
    index=False
)

satisfaction.to_sql(
    name='satisfaction',
    con=engine,
    if_exists='append',
    index=False
)

# Final verification
with engine.connect() as conn:
    for table in ['departments','employees','job_details','satisfaction']:
        count = conn.execute(text(f"SELECT COUNT(*) FROM {table}")).fetchone()[0]
        print(f"{table}: {count} rows")

In [31]:
test = pd.read_sql(
    "SELECT * FROM employee_full LIMIT 5",
    engine
)
print(test.shape)   # Should be (5, 30)
print(test.columns.tolist())

(5, 32)
['employee_id', 'age', 'gender', 'marital_status', 'education', 'education_field', 'distance_from_home', 'num_companies_worked', 'total_working_years', 'attrition', 'department_name', 'job_role', 'job_level', 'business_travel', 'overtime', 'monthly_income', 'hourly_rate', 'daily_rate', 'monthly_rate', 'percent_salary_hike', 'stock_option_level', 'training_times_last_year', 'years_at_company', 'years_in_current_role', 'years_since_last_promotion', 'years_with_curr_manager', 'job_satisfaction', 'environment_satisfaction', 'relationship_satisfaction', 'work_life_balance', 'job_involvement', 'performance_rating']

## Preparing data for ML and SHAP

In [ ]:
pip install shap

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import (classification_report, confusion_matrix, roc_auc_score, roc_curve)
from imblearn.over_sampling import SMOTE
import shap
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
df_ml = pd.read_sql("SELECT * FROM employee_full", engine)

print(f'Shape: {df_ml.shape}')
print(f'Attrition rate: {df_ml["attrition"].mean()*100:.1f}%')
print(f'\nColumn types:')
print(df_ml.dtypes)

Shape: (1470, 32)
Attrition rate: 16.1%

Column types:
employee_id                    int64
age                            int64
gender                        object
marital_status                object
education                      int64
education_field               object
distance_from_home             int64
num_companies_worked           int64
total_working_years            int64
attrition                      int64
department_name               object
job_role                      object
job_level                      int64
business_travel               object
overtime                      object
monthly_income                 int64
hourly_rate                    int64
daily_rate                     int64
monthly_rate                   int64
percent_salary_hike            int64
stock_option_level             int64
training_times_last_year       int64
years_at_company               int64
years_in_current_role          int64
years_since_last_promotion     int64
years_with_curr_manager        int64
job_satisfaction               int64
environment_satisfaction       int64
relationship_satisfaction      int64
work_life_balance              int64
job_involvement                int64
performance_rating             int64
dtype: object

### Checking class distribution

In [35]:
attrition_counts = df_ml['attrition'].value_counts()
attrition_pct = df_ml['attrition'].value_counts(normalize=True) * 100

print('Class Distribution:')
print(f'Stayed (0): {attrition_counts[0]:,}  ({attrition_pct[0]:.1f}%)')
print(f'Left (1): {attrition_counts[1]:,}  ({attrition_pct[1]:.1f}%)')
print(f'\nImbalance ratio: {attrition_counts[0]/attrition_counts[1]:.1f}:1')

Class Distribution:
Stayed (0): 1,233  (83.9%)
Left (1): 237  (16.1%)

Imbalance ratio: 5.2:1

## Feature Engineering

In [37]:
drop_cols = [
    'attrition',          # target variable
    'employee_id',        # unique identifier - no predictive signal
    'hourly_rate',        # redundant with monthly_income
    'daily_rate',         # redundant with monthly_income
    'monthly_rate',       # different from monthly_income, less reliable
]

# Separate features and target
X = df_ml.drop(columns=drop_cols)
y = df_ml['attrition']

print(f'Features shape:{X.shape}')
print(f'Target shape:{y.shape}')
print(f'\nFeature columns ({X.shape[1]}):')
print(X.columns.tolist())

Features shape:(1470, 27)
Target shape:(1470,)

Feature columns (27):
['age', 'gender', 'marital_status', 'education', 'education_field', 'distance_from_home', 'num_companies_worked', 'total_working_years', 'department_name', 'job_role', 'job_level', 'business_travel', 'overtime', 'monthly_income', 'percent_salary_hike', 'stock_option_level', 'training_times_last_year', 'years_at_company', 'years_in_current_role', 'years_since_last_promotion', 'years_with_curr_manager', 'job_satisfaction', 'environment_satisfaction', 'relationship_satisfaction', 'work_life_balance', 'job_involvement', 'performance_rating']

##  Encoding Categorical Columns

In [38]:
# Identifying categorical columns
cat_cols = X.select_dtypes(include='object').columns.tolist()
print(f'Categorical columns to encode: {cat_cols}')

# Label encode each one
le = LabelEncoder()
X_encoded = X.copy()

for col in cat_cols:
    X_encoded[col] = le.fit_transform(X_encoded[col])
    print(f'{col}: {X[col].unique()} → {X_encoded[col].unique()}')

print(f'\nAll dtypes after encoding:')
print(X_encoded.dtypes.value_counts())

Categorical columns to encode: ['gender', 'marital_status', 'education_field', 'department_name', 'job_role', 'business_travel', 'overtime']
gender: ['Female' 'Male'] → [0 1]
marital_status: ['Single' 'Married' 'Divorced'] → [2 1 0]
education_field: ['Life Sciences' 'Marketing' 'Technical Degree' 'Medical' 'Other'
 'Human Resources'] → [1 2 5 3 4 0]
department_name: ['Sales' 'Research & Development' 'Human Resources'] → [2 1 0]
job_role: ['Sales Executive' 'Manager' 'Sales Representative' 'Research Scientist'
 'Laboratory Technician' 'Manufacturing Director'
 'Healthcare Representative' 'Research Director' 'Human Resources'] → [7 3 8 6 2 4 0 5 1]
business_travel: ['Travel_Rarely' 'Travel_Frequently' 'Non-Travel'] → [2 1 0]
overtime: ['Yes' 'No'] → [1 0]

All dtypes after encoding:
int64    27
Name: count, dtype: int64

## Train Test Split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42, stratify=y)
# preserves 84/16 ratio in both train and test


print(f'Training set: {X_train.shape[0]:,} rows')
print(f'Test set: {X_test.shape[0]:,} rows')
print(f'\nClass distribution in training set:')
print(y_train.value_counts())
print(f'\nClass distribution in test set:')
print(y_test.value_counts())

Training set: 1,176 rows
Test set: 294 rows

Class distribution in training set:
attrition
0    986
1    190
Name: count, dtype: int64

Class distribution in test set:
attrition
0    247
1     47
Name: count, dtype: int64

## Applying SMOTE to Training Data Only

In [40]:
smote = SMOTE(random_state=42)
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

print('Before SMOTE:')
print(f'Stayed: {(y_train==0).sum():,}')
print(f'Left: {(y_train==1).sum():,}')

print('\nAfter SMOTE:')
print(f'Stayed:{(y_train_sm==0).sum():,}')
print(f'Left:{(y_train_sm==1).sum():,}')

print(f'\nTraining set size after SMOTE: {len(X_train_sm):,} rows')

Before SMOTE:
Stayed: 986
Left: 190

After SMOTE:
Stayed:986
Left:986

Training set size after SMOTE: 1,972 rows

## Training All Three Models

In [41]:
models = {'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42), 
          'Random Forest': RandomForestClassifier( n_estimators=100,random_state=42),
          'XGBoost': XGBClassifier( n_estimators=100, learning_rate=0.1, max_depth=4, random_state=42, eval_metric='logloss', verbosity=0)}

results = {}

for name, model in models.items():
    model.fit(X_train_sm, y_train_sm)
    y_pred = model.predict(X_test)
    y_pred_prob = model.predict_proba(X_test)[:, 1]
    results[name] = {'model': model, 'y_pred': y_pred, 'y_prob': y_pred_prob, 'roc_auc': roc_auc_score(y_test, y_pred_prob)}
    
    print(f'\n{"="*50}')
    print(f'{name}')
    print(f'{"="*50}')
    print(classification_report(y_test, y_pred, target_names=['Stayed','Left']))
    print(f'ROC-AUC Score: {results[name]["roc_auc"]:.3f}')

==================================================
Logistic Regression
==================================================
              precision    recall  f1-score   support

      Stayed       0.90      0.79      0.84       247
        Left       0.33      0.53      0.41        47

    accuracy                           0.75       294
   macro avg       0.61      0.66      0.62       294
weighted avg       0.81      0.75      0.77       294

ROC-AUC Score: 0.747

==================================================
Random Forest
==================================================
              precision    recall  f1-score   support

      Stayed       0.89      0.95      0.92       247
        Left       0.58      0.38      0.46        47

    accuracy                           0.86       294
   macro avg       0.74      0.67      0.69       294
weighted avg       0.84      0.86      0.84       294

ROC-AUC Score: 0.745

==================================================
XGBoost
==================================================
              precision    recall  f1-score   support

      Stayed       0.90      0.93      0.92       247
        Left       0.56      0.47      0.51        47

    accuracy                           0.86       294
   macro avg       0.73      0.70      0.71       294
weighted avg       0.85      0.86      0.85       294

ROC-AUC Score: 0.779

## Comparing Models in One Clean Table

In [ ]:
comparison = pd.DataFrame([{'Model': name, 'ROC-AUC': round(r['roc_auc'], 3), 
                            'Report': classification_report( y_test, r['y_pred'], target_names=['Stayed','Left'],output_dict=True)}
                           for name, r in results.items()])

# Build clean summary
summary_rows = []
for name, r in results.items():
    report = classification_report(
        y_test, r['y_pred'],
        target_names=['Stayed','Left'],
        output_dict=True
    )
    summary_rows.append({
        'Model'           : name,
        'ROC-AUC'         : round(r['roc_auc'], 3),
        'Precision (Left)': round(report['Left']['precision'], 3),
        'Recall (Left)'   : round(report['Left']['recall'], 3),
        'F1 (Left)'       : round(report['Left']['f1-score'], 3),
        'Overall Accuracy': round(report['accuracy'], 3),
    })

summary_df = pd.DataFrame(summary_rows)
print(summary_df.to_string(index=False))